### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Mehranalam** [PariKhaleghi/PariKhaleghi#1]
I think using github Action can be very useful for you and give a more beautiful effect to your github profile, I suggest you check this link, and promote your useful blog posts inside github.

https://github.com/simonw/simonw

If you agree, can I spend time on this part of your profile in my free time?  It can certainly be very good.

**Comment by PariKhaleghi** [comment]
> I think using github Action can be very useful for you and give a more beautiful effect to your github profile, I suggest you check this link, and promote your useful blog posts inside github.
> 
> https://github.com/simonw/simonw
> 
> If you agree, can I spend time on this part of your profile in my free time? It can certainly be very good.

it's very interesting. I think I I've seen this page and its profile before.  Really attractive. If it happens, it'll be very good, but in the words of us Iranians: زحمت می‌شه براتون. 😁🌹 I really don't wanna bother you, if you are free and bored, thank you for doing it, otherwise don't bother yourself.
Thank U again. 🌺

**Comment by Mehranalam** [comment]
درکل زحمتی نیست بیش تر میتونه تجربه و علم من رو در بخش **گیت هاب اکشن** و **نحوه استفاده اش** بیشتر کنه و هم کاری مفید انجام بشه .😄🌷🌷🌹

**Comment by PariKhaleghi** [comment]
> درکل زحمتی نیست بیش تر میتونه تجربه و علم من رو در بخش **گیت هاب اکشن** و **نحوه استفاده اش** بیشتر کنه و هم کاری مفید انجام بشه .😄🌷🌷🌹

دست شما درد نکنه.
امیدوارم بتونم جبران کنم. 🌻
